---
- name: set up sbc environments
  hosts: 
    - rpis
    - zblades
  become: yes

  tasks: 

  - name: install zsh, fzf zoxide, and replacement shell utils
    apt:
      pkg:
      - zsh
      - fzf
      - zoxide
      - bat
      - eza
      - btop
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: set user scoot shell to zsh
    user:
      name: scoot
      shell: /bin/zsh

  - name: Copy zsh rc files into ~/
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}" 
      owner: scoot
      group: scoot
      mode: 0644
    with_items:
      - src: "dotfiles/.zshrc"
        dest: "~/.zshrc"
      - src: "dotfiles/.p10k.zsh"
        dest: "~/.p10k.zsh"
        #      - src: "dotfiles/.tmux.conf"
        #        dest: "~/.tmux.conf"
    become: no

  - name: install git, password-store, neovim, tmux, etc
    apt:
      pkg:
      - git
      - neovim
      #      - tmux
      - pass
      state: present

      # TOD0: ansiblize this
      #sudo mkdir -p /etc/apt/keyrings
      #wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
      #echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
      #sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
      #sudo apt update
      #sudo apt install -y eza  
      #  - name: Git checkout tpm, tmux plugin manager
      #    ansible.builtin.git:
      #      repo: 'https://github.com/tmux-plugins/tpm'
      #      dest: ~/.tmux/plugins/tpm
      #    become: no
