---
- name: set up sbc environments
  hosts: 
    - rpis
    - zblades
  become: yes
  gather_facts: no

  tasks: 

  - name: add eza repo and key
    block:
      - name: somerepo | no apt key
        ansible.builtin.get_url:
          url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
          dest: /etc/apt/keyrings/gierens.asc
          #checksum: sha256:bb42f0db45d46bab5f9ec619e1a47360b94c27142e57aa71f7050d08672309e0

      - name: somerepo | apt source
        ansible.builtin.apt_repository:
          repo: "deb [signed-by=/etc/apt/keyrings/gierens.asc] http://deb.gierens.de stable main"
          state: present

  - name: install zsh, fzf zoxide, and replacement shell utils
    apt:
      pkg:
      - zsh
      - fzf
      - zoxide
      - bat
      - eza
      - btop
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: set user scoot shell to zsh
    user:
      name: scoot
      shell: /bin/zsh

  - name: install git, password-store
    apt:
      pkg:
      - git
      - pass
      state: present

- name: set up configs
  hosts: 
    - rpis
    - zblades
    - windoze
  become: yes
  gather_facts: no

  tasks: 

  - name: Copy zsh/p10k dotfiles files into ~/
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}" 
      owner: scoot
      group: users
      mode: 0644
    with_items:
      - src: "dotfiles/.zshrc"
        dest: "~/.zshrc"
      - src: "dotfiles/wezterm.lua"
        dest: "~/.config/wezterm/wezterm.lua"
      - src: "dotfiles/.p10k.zsh"
        dest: "~/.p10k.zsh"
        #      - src: "dotfiles/.tmux.conf"
        #        dest: "~/.tmux.conf"
    become: no

  - name: Copy btop config files into ~/.config
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}" 
      owner: scoot
      group: users
      mode: 0644
    with_items:
      - src: "configfiles/btop"
        dest: "~/.config"
    become: no

