- name: set up sbc homelabs
  hosts: 
    - rpis
    - zblades
  become: yes

  tasks: 

  - name: install docker and compose
    apt:
      pkg:
      - docker.io
      - docker-compose
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: add scoot to docker group
    user:
      name: scoot
      groups: docker
      append: true # don't remove existing groups

  # Pulls the portainer image (Ubuntu)
  - name: Pull portainer image
    community.docker.docker_image:
      name: "portainer/portainer-ce:linux-amd64"
      source: pull

  - name: Create portainer container
    community.docker.docker_container:
      name: "portainer"
      image: "portainer/portainer-ce:linux-amd64"
      restart_policy: always
      state: started
      ports:
        - 9000:9000
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
