---
- name: setup neovim
  hosts: 
  - rpis
  - zblades

  tasks: 

  # Update to use neovim 10
  - name: install neovim
    apt:
      pkg:
      - neovim
      state: present
      update_cache: yes
      cache_valid_time: 3600
    become: yes

  - name: Git checkout NvChad
    ansible.builtin.git:
      repo: 'https://github.com/NvChad/NvChad'
      dest: "~/.config/nvim"
      depth: 1
