---
- name: setup zfs
  hosts: 
  - rpis
  - zblades

  tasks: 

  - name: install zfs kernal modules and utils
    apt:
      pkg:
      - zfs-dkms
      - zfsutils-linux
      - sanoid
      - samba
      state: present
      update_cache: yes
      cache_valid_time: 3600
    become: yes
